FROM node:20-slim

# Instala dependências básicas do sistema necessárias
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho interno
WORKDIR /usr/src/app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências de forma limpa
RUN npm install

# Copia o restante do código do bot
COPY . .

# Comando para iniciar a Ellena
CMD ["node", "index.js"]
